### ISSUE TITLE
limit autocomplete suggestions to those that already match

### ISSUE THREAD

**Issue by zapp29** [xcash/bootstrap-autocomplete#41] opened 2019-11-10 18:15 UTC
I have a long list in my json. When I start typing in, the long list of all the options pops up. Most of the options displayed of course do not match the characters from input.

Is it possible in the current version to set it up (without much work ;) ) in that way that only those options that are already matching the characters are displayed ? If not - could it be added in the future releases ?

Please let me know if my description is not clear enough.

**Comment by xcash** [comment] 2019-11-20 10:16
Hi @zapp29,
The library acts this way by design cause it's common to filter results server-side and not client side.
That's why it does a remote query with a `qry` parameter.

You can override the `search` event and return a custom filtered list of results.
Take a look here on how to implement such override: https://github.com/xcash/bootstrap-autocomplete/blob/master/src/index4.html#L200

Implementing a custom filter is trivial, let me know if you need a deeper example. I'll close this for now. :)

**Closed by xcash** 2019-11-20 10:16 UTC
Labels: wontfix

**Comment by marekmez** [comment] 2020-05-04 18:55
Hi @xcash,

I have been trying to filter results as you explained above. But have not been able to make it work with `select` element.

This is what I have done:
```
$('element-selector').autoComplete({
            resolver: 'custom',
            events: {
                search: function (qry, callback) {
                    $.ajax(
                        "json/search/",
                        {
                            data: { 'qry': qry}
                        }
                    ).done(function (res) {
                        callback(res.results)
                    });
                }
            }
        });
```

Server returns json in this format:
[{"value":111,"text":"Test seach string"},{...},...]

But having this issue:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at DropdownV4.refreshItemList (dropdown.ts:369)
    at DropdownV4.updateItems (dropdown.ts:352)
    at AutoComplete.handlerStartShow (main.ts:344)
    at AutoComplete.postSearchCallback (main.ts:339)
    at eval (main.ts:318)
    at Object.<anonymous> (create:158)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

If I manualy call url with /?qry=something it works fine on server side.

**Comment by xcash** [comment] 2020-05-05 15:04
Hi @marekmez 

In my example the server returned a different json from yours with a top-level key "results".
For you return forma you probably just need `callback(res)` (without .results)

**Comment by tottlefields** [comment] 2021-02-16 10:42
So, I am having a very similar issue.... I want to use tis library with an ajax call. I have set my code up exactly as shown above (I think...) and can confirm that my server is giving a json response that matches the structure suggested in teh docs, yet I still get the "Cannot read property 'length' of undefined" error.

```
<script>
	$(document).ready(function(){
		$('.advancedAutoComplete').autoComplete({
			resolver: 'custom',
			events: {
				search: function (qry, callback) {
					// let us do a custom ajax call
					$.ajax(
						'data/dogSearch.php', {
							data: { 'qry': qry}
						}
					).done(function (res) {
						callback(res.results)
					});
				}
			}
		});
	});
</script>';
```

The structure of "res"...
```
{ results: [
	{ id: "tottlefields-bee-a-star", text: "Tottlefields Bee a Star" },
	{ id: "tottlefields-bee-amazin", text: "Tottlefields Bee Amazin'" },
	{ id: "tottlefields-bee-happy", text: "Tottlefields Bee Happy" }
] }
```

Can anybody spot what I have done wrong please, or help me get this working.

Great library and hope I can get it working.

Thanks,
Ellen.

**Comment by xcash** [comment] 2021-02-16 10:48
Hi @tottlefields 
The code seems right.
Maybe your php page doesn't return the correct content-type: `application/json` ?

**Comment by tottlefields** [comment] 2021-02-16 10:55
OMG, thank you!!!!! That has been doing my head in for 12 hours now. Works perfectly with the right header on the php script.

Thanks so much and apologies for being a numpty.

Ellen.

**Comment by xcash** [comment] 2021-02-16 11:51
Hi @tottlefields 
I'm glad it helped. :)
