### ISSUE TITLE
Request Throttling not working with ajax resolver

### ISSUE THREAD

**Issue by hoangthGitHub** [xcash/bootstrap-autocomplete#87] opened 2020-09-02 01:23 UTC
hi,
I am using
resolver:'ajax',
resolverSettings:{ requestthrottling: 2000},
 requestthrottling: 2000

**Comment by bluerhinos** [comment] 2020-09-12 09:45
I solved it for me in a messy way using the custom function it waits 500ms before sending a query (and if a key is press it delays it)
```js
$('.findItem').autoComplete({
        resolver: 'custom',
        events: {
            search: function (qry, callback, jq) {
                if(this._timeout) {
                    clearTimeout(this._timeout);
                }
                this._timeout = setTimeout(
                    function() {
                        // let's do a custom ajax call
                        $.ajax(
                            '<URL>',
                            {
                                data: { 'qry' : qry}
                            }
                        ).done(function (res) {
                            callback(res.data)
                        });
                    }, 500
                );
            }
        }
    })
```

**Comment by xcash** [comment] 2020-09-16 15:36
duplicate of #78

**Closed by xcash** 2020-09-16 15:36 UTC
Labels: wontfix
