### ISSUE TITLE
PreventDefault on with mod_rewrite

### ISSUE THREAD

**Issue by rejustify** [xcash/bootstrap-autocomplete#51] opened 2020-03-15 20:41 UTC
The script works great but when mod_rewrite is on, after selecting an item from the list, the script submits the form by default, redirecting to the next page. It is quite tricky to set preventDefault on the form:

    $('.item').autoComplete({	
		resolver: 'custom',
		formatResult: function (item) {
			return {
				value: item.id,
				text:  item.desc + " [" + item.name + "] "
			};
		},
		select: function(e){
			e.preventDefault();
		}
		events: {
			search: function (qry, callback, origJQElement) {
				$.ajax({
   					 type: "POST",
   					 url: "search.php",
					 data: { 'qry': qry},
					 dataType: "json"
				}).done(function (res) {
					callback(res.results);
				});
				
			}
		},
	});

**Comment by xcash** [comment] 2020-03-24 17:48
Duplicate of #37

**Closed by xcash** 2020-03-24 17:48 UTC
