### ISSUE TITLE
preventEnter: true not working

### ISSUE THREAD

**Issue by LouisBellinger** [xcash/bootstrap-autocomplete#59] opened 2020-04-16 10:59 UTC
**Describe the bug**

I've set preventEnter: true to prevent form submit when selecting an item in the dropdown, but still, my form is submited each time the "enter" key is pressed while hovering an item inside the dropdown. 

**Expected behavior**
The hovered item is selected but the form is not submitted.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Mozilla 75.0 (64-bit)

EDIT: Did this ugly fix in the meantime:

$('#id_q').on('autocomplete.dd.hidden', function(e, item) {
    $('#searchform').addClass('nosubmit');
});

$('#searchform').on('keypress', function(e) {
    var keyCode = e.keyCode || e.which;
    if (keyCode === 13 && $('#searchform').hasClass('nosubmit')) {
        e.preventDefault();
        $('#searchform').removeClass('nosubmit');
        return false;
    }
});

**Comment by jfstenuit** [comment] 2020-04-28 19:44
Same issue here.

Init code is :
```
$( "input.autocomplete" ).autoComplete({
		resolverSettings: {
			url: 'autocomplete.php'
		},
		preventEnter: true
	});
```

**Comment by xcash** [comment] 2020-04-29 18:02
It's now fixed in the unstable version. 
You can try it or wait for a full release. 
Sorry for that.

**Closed** 2020-04-29 18:03 UTC
Labels: bug

**Comment by LouisBellinger** [comment] 2020-05-05 14:39
Your fix totally prevent form submission, while the point was to prevent the form submission **only** when selecting an item from the dropdown with "enter".

I think totally preventing the form submission should be handled by the end user.

**Comment by xcash** [comment] 2020-05-05 15:01
@LouisBellinger uhm... i made some tests and it works as intended (and as you outlined).
https://jsfiddle.net/9dnc68aw/12/

HTML forms have some caveats :) If you have only one input the Enter will submit,
if you have 2 input and no input with a type submit Enter won't do anything.
If you have 2 or more input and an input type submit (or a button type submit) Enter will submit.

**Comment by LouisBellinger** [comment] 2020-05-06 14:59
@xcash based on your fiddle: I meant that, if I select a row by pressing "enter", then pressing "enter" another time should submit the form. That's not the case as of now.
