### ISSUE TITLE
on page Links lead to localhost

### ISSUE THREAD

**Issue by alagoroVigo** [xcash/bootstrap-autocomplete#47] opened 2019-12-01 13:40 UTC
On the page:
https://bootstrap-autocomplete.readthedocs.io/en/stable/

Te links:
"Demo page"
"Documentation"

lead to localhost so error page is shown.

**Comment by xcash** [comment] 2019-12-18 09:37
Duplicate of #42

**Closed by xcash** 2019-12-18 09:37 UTC
